# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98488ca0fd26f6a16f8a72458d3978fbd3e19b317e948b748e586b5746836ce7576bf5564fd8c6d58f956b2e13ac8d0f04ca5c1154bdeb274c1c34f6ef530cd4

test:
  secret_key_base: 874bd50c289425be18112b8dfe7d00f32b3378d59980420121e94320729daa0566512bccb17dd7848fa372e28ae7c2ca77fdf208af2c9f721abcc266a922594e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
